//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Characters/Player/Scripts/PlayerCam.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerCam: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerCam()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerCam"",
    ""maps"": [
        {
            ""name"": ""Playercinem"",
            ""id"": ""a3a5bbb7-9213-4f41-aa04-196764f5bc3b"",
            ""actions"": [
                {
                    ""name"": ""look"",
                    ""type"": ""Value"",
                    ""id"": ""cd9cd8ca-1be6-4e4f-96dd-de4ce52c1511"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bd96b2a7-0a98-4b55-9146-5541605ab223"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Playercinem
        m_Playercinem = asset.FindActionMap("Playercinem", throwIfNotFound: true);
        m_Playercinem_look = m_Playercinem.FindAction("look", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Playercinem
    private readonly InputActionMap m_Playercinem;
    private List<IPlayercinemActions> m_PlayercinemActionsCallbackInterfaces = new List<IPlayercinemActions>();
    private readonly InputAction m_Playercinem_look;
    public struct PlayercinemActions
    {
        private @PlayerCam m_Wrapper;
        public PlayercinemActions(@PlayerCam wrapper) { m_Wrapper = wrapper; }
        public InputAction @look => m_Wrapper.m_Playercinem_look;
        public InputActionMap Get() { return m_Wrapper.m_Playercinem; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayercinemActions set) { return set.Get(); }
        public void AddCallbacks(IPlayercinemActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayercinemActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayercinemActionsCallbackInterfaces.Add(instance);
            @look.started += instance.OnLook;
            @look.performed += instance.OnLook;
            @look.canceled += instance.OnLook;
        }

        private void UnregisterCallbacks(IPlayercinemActions instance)
        {
            @look.started -= instance.OnLook;
            @look.performed -= instance.OnLook;
            @look.canceled -= instance.OnLook;
        }

        public void RemoveCallbacks(IPlayercinemActions instance)
        {
            if (m_Wrapper.m_PlayercinemActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayercinemActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayercinemActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayercinemActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayercinemActions @Playercinem => new PlayercinemActions(this);
    public interface IPlayercinemActions
    {
        void OnLook(InputAction.CallbackContext context);
    }
}
